/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Cliente;
import Clases.Counter;
import Mail.SendMail;
import java.util.Random;
import java.util.stream.IntStream;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Chavas
 */
public class CreacionCuenta extends javax.swing.JFrame {
    
    /**
     * Creates new form CreacionCuenta
     */
    public CreacionCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        LTitulo = new javax.swing.JLabel();
        Sexo = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        FechaN = new javax.swing.JLabel();
        BCrear = new javax.swing.JButton();
        CBSexo = new javax.swing.JComboBox();
        CNombre = new javax.swing.JTextField();
        CApellido = new javax.swing.JTextField();
        CCorreo = new javax.swing.JTextField();
        CNumero = new javax.swing.JTextField();
        CDireccion = new javax.swing.JTextField();
        LNombre = new javax.swing.JLabel();
        LApellido = new javax.swing.JLabel();
        LCorreo = new javax.swing.JLabel();
        LNumero = new javax.swing.JLabel();
        CBDia = new javax.swing.JComboBox();
        CBMes = new javax.swing.JComboBox();
        CBAño = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LConsulta = new javax.swing.JLabel();
        CConsulta = new javax.swing.JTextField();
        BConsulta = new javax.swing.JButton();
        Sexo1 = new javax.swing.JLabel();
        Direccion1 = new javax.swing.JLabel();
        FechaN1 = new javax.swing.JLabel();
        CNombre1 = new javax.swing.JTextField();
        CApellido1 = new javax.swing.JTextField();
        CCorreo1 = new javax.swing.JTextField();
        CNumero1 = new javax.swing.JTextField();
        CDireccion1 = new javax.swing.JTextField();
        LNombre1 = new javax.swing.JLabel();
        LApellido1 = new javax.swing.JLabel();
        LCorreo1 = new javax.swing.JLabel();
        LNumero1 = new javax.swing.JLabel();
        BEditar = new javax.swing.JButton();
        BBorrar = new javax.swing.JButton();
        CSexo = new javax.swing.JTextField();
        CFecha = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTitulo.setText("Bienvenido nuevo usuario Favor llenar los espacios con lo solicitado.Nota: Debe ser Mayor de edad ");

        Sexo.setText("Sexo");

        Direccion.setText("Direccion");

        FechaN.setText("Fecha de Nacimiento DD/MM/YY");

        BCrear.setText("Crear");
        BCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCrearActionPerformed(evt);
            }
        });

        CBSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));
        CBSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSexoActionPerformed(evt);
            }
        });

        CNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNombreActionPerformed(evt);
            }
        });

        CDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDireccionActionPerformed(evt);
            }
        });

        LNombre.setText("Nombre");

        LApellido.setText("Apellido");

        LCorreo.setText("Correo");

        LNumero.setText("Numero Telefonico ");

        CBDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CBDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDiaActionPerformed(evt);
            }
        });

        CBMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        CBAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97" }));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LTitulo)
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LApellido)
                            .addComponent(LNombre)
                            .addComponent(LCorreo)
                            .addComponent(Sexo)
                            .addComponent(Direccion)
                            .addComponent(LNumero)
                            .addComponent(FechaN))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CBSexo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CBDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(CBMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(CBAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(BCrear)))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNombre)
                            .addComponent(CNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LApellido)
                            .addComponent(CApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sexo)
                    .addComponent(CBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaN)
                    .addComponent(CBMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jTabbedPane1.addTab("Creacion de Cuenta", jPanel1);

        LConsulta.setText("Escriba el nombre del Identificador");

        CConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CConsultaActionPerformed(evt);
            }
        });

        BConsulta.setText("Consultar");
        BConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultaActionPerformed(evt);
            }
        });

        Sexo1.setText("Sexo");

        Direccion1.setText("Direccion");

        FechaN1.setText("Fecha de Nacimiento DD/MM/YY");

        CNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNombre1ActionPerformed(evt);
            }
        });

        CDireccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDireccion1ActionPerformed(evt);
            }
        });

        LNombre1.setText("Nombre");

        LApellido1.setText("Apellido");

        LCorreo1.setText("Correo");

        LNumero1.setText("Numero Telefonico ");

        BEditar.setText("Editar");
        BEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditarActionPerformed(evt);
            }
        });

        BBorrar.setText("Borrar");
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaN1)
                            .addComponent(LNombre1)
                            .addComponent(LApellido1)
                            .addComponent(LNumero1)
                            .addComponent(Direccion1)
                            .addComponent(LCorreo1)
                            .addComponent(Sexo1))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(BEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BBorrar))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(CNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(CDireccion1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BConsulta))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CFecha, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CSexo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CCorreo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BConsulta)
                    .addComponent(LConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNombre1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LApellido1)
                    .addComponent(CApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNumero1)
                    .addComponent(CNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCorreo1)
                    .addComponent(CCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sexo1)
                    .addComponent(CSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaN1)
                    .addComponent(CFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBorrar)
                    .addComponent(BEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        jTabbedPane1.addTab("Consulta", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNombreActionPerformed

    }//GEN-LAST:event_CNombreActionPerformed
private String Identificador()
{
        int pos;
        pos = new Random().nextInt(26);
        numero=numero+pos;
        StringBuilder sb = new StringBuilder();
        sb.append("");
        sb.append(numero);
        String Numero = sb.toString();
        String Identificador ;
        char letra=letras.charAt( pos );
        Identificador = Numero+letra;
        return Identificador;
}
private boolean EmailValidate(String email)
{  
    String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
    java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
    java.util.regex.Matcher m = p.matcher(email);
    return m.matches();
}

    private void BCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCrearActionPerformed
       String Telefono = CNumero.getText();
       String Correo = CCorreo.getText();
       String Apellido = CApellido.getText();
       String Nombre= CNombre.getText(); 
       String Identificador=Identificador();
       String Sexo= CBSexo.getSelectedItem().toString(); 
       String Direccion=CDireccion.getText();
       String fecha= CBDia.getSelectedItem().toString()+"/"+CBMes.getSelectedItem().toString()+"/"+CBAño.getSelectedItem().toString(); 
       if (CNumero.getText().isEmpty()||CCorreo.getText().isEmpty()||CApellido.getText().isEmpty()||CNombre.getText().isEmpty()||CDireccion.getText().isEmpty())
       {
          JOptionPane.showMessageDialog(null, "Tienes que llenar todos los campos para crear la cuenta");    
       }
       else
       {
           if (EmailValidate(Correo))
           {
               if (Telefono.length()>5)
               {
               mail=new SendMail(Correo,"Gracias por registrarte",CNombre.getText());
               Cliente Cuenta=new Cliente(Nombre,Apellido,Identificador, Correo,Telefono, Direccion, Sexo, fecha,"Normal");
               CrearCounter.counter.AsignarCasillero(Cuenta);
               CrearCounter.counter.AgregarClientes(Cuenta);
               
               JOptionPane.showMessageDialog(null, "El Cliente se ha registrado exitosamente");  
               }
               else
               {
                  JOptionPane.showMessageDialog(null, "El telefono tiene que tener una catidad de numeros mayor a 5");  
                
               }
           }
           else
           {
                         JOptionPane.showMessageDialog(null, "Email invalido");
           }
       }     
    }//GEN-LAST:event_BCrearActionPerformed

    private void CDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDireccionActionPerformed

    private void CBSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBSexoActionPerformed

    private void CDireccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDireccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDireccion1ActionPerformed

    private void CNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNombre1ActionPerformed

    private void BConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultaActionPerformed
        String Ident=CConsulta.getText();
        Cliente cliente=CrearCounter.counter.BusquedaCliente(Ident);
        if (cliente == null)
        {
        }
        else
        {
           CNombre1.setText(cliente.getNombre());
           CApellido1.setText(cliente.getApellido());
           CNumero1.setText(cliente.getTelefono());
           CDireccion1.setText(cliente.getDireccion());
           CCorreo1.setText(cliente.getCorreo());
           CSexo.setText(cliente.getSexo());
           CFecha.setText(cliente.getFechaN());    
        }  
    }//GEN-LAST:event_BConsultaActionPerformed

    private void CConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CConsultaActionPerformed

    private void CBDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBDiaActionPerformed

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
    String Ident=CConsulta.getText();
    CrearCounter.counter.EliminarCliente(Ident);
    }//GEN-LAST:event_BBorrarActionPerformed

    private void BEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditarActionPerformed
       String Ident=CConsulta.getText();
       Cliente cliente=CrearCounter.counter.BusquedaCliente(Ident);
       String Telefono = CNumero1.getText();
       String Correo = CCorreo1.getText();
       String Apellido = CApellido1.getText();
       String Nombre= CNombre1.getText();
       String Sexo= CBSexo.getSelectedItem().toString(); 
       String Direccion=CDireccion1.getText();
       String fecha= CFecha.getText();
       if (CNumero1.getText().isEmpty()||CCorreo1.getText().isEmpty()||CApellido1.getText().isEmpty()||CNombre1.getText().isEmpty()||CDireccion1.getText().isEmpty()||CFecha.getText().isEmpty())
       {
          JOptionPane.showMessageDialog(null, "Tienes que llenar todos los campos para crear la cuenta");    
       }
       else
       {
           if (EmailValidate(Correo))
           {   
               cliente.setCorreo(Correo);
               cliente.setDireccion(Direccion);
               cliente.setFechaN(fecha);
               cliente.setNombre(Nombre);
               cliente.setSexo(Sexo);
               cliente.setTelefono(Telefono);              
               System.out.println(cliente.toString());
               JOptionPane.showMessageDialog(null, "La informacion se ha editado exitosamente");      
           }
           else
           {
                         JOptionPane.showMessageDialog(null, "Email invalido");
           }
       }
    }//GEN-LAST:event_BEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionCuenta().setVisible(true);
            }
        });
    }
    
    public final String letras="adbcefghijklmnopqrestuvwxyz"; 
    public int numero=0;
    public SendMail mail ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BConsulta;
    private javax.swing.JButton BCrear;
    private javax.swing.JButton BEditar;
    private javax.swing.JTextField CApellido;
    private javax.swing.JTextField CApellido1;
    private javax.swing.JComboBox CBAño;
    private javax.swing.JComboBox CBDia;
    private javax.swing.JComboBox CBMes;
    private javax.swing.JComboBox CBSexo;
    private javax.swing.JTextField CConsulta;
    private javax.swing.JTextField CCorreo;
    private javax.swing.JTextField CCorreo1;
    private javax.swing.JTextField CDireccion;
    private javax.swing.JTextField CDireccion1;
    private javax.swing.JTextField CFecha;
    private javax.swing.JTextField CNombre;
    private javax.swing.JTextField CNombre1;
    private javax.swing.JTextField CNumero;
    private javax.swing.JTextField CNumero1;
    private javax.swing.JTextField CSexo;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Direccion1;
    private javax.swing.JLabel FechaN;
    private javax.swing.JLabel FechaN1;
    private javax.swing.JLabel LApellido;
    private javax.swing.JLabel LApellido1;
    private javax.swing.JLabel LConsulta;
    private javax.swing.JLabel LCorreo;
    private javax.swing.JLabel LCorreo1;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LNombre1;
    private javax.swing.JLabel LNumero;
    private javax.swing.JLabel LNumero1;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JLabel Sexo;
    private javax.swing.JLabel Sexo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
//Setters Getters
    //Getters
    public JTextField getCApellido1() {
        return CApellido1;
    }

    public JTextField getCCorreo1() {
        return CCorreo1;
    }

    public JTextField getCDireccion1() {
        return CDireccion1;
    }

    public JTextField getCNombre1() {
        return CNombre1;
    }

    public JTextField getCNumero1() {
        return CNumero1;
    }


    //setters 
    public void setCApellido1(JTextField CApellido1) {
        this.CApellido1 = CApellido1;
    }


    public void setCCorreo1(JTextField CCorreo1) {
        this.CCorreo1 = CCorreo1;
    }

    public void setCDireccion1(JTextField CDireccion1) {
        this.CDireccion1 = CDireccion1;
    }

    public void setCNombre1(JTextField CNombre1) {
        this.CNombre1 = CNombre1;
    }

    public void setCNumero1(JTextField CNumero1) {
        this.CNumero1 = CNumero1;
    }


    
}
