/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Counter;
import javax.swing.JOptionPane;

/**
 *
 * @author Chavas
 */
public class CrearCounter extends javax.swing.JFrame {
    public static Counter counter=null;
    /**
     * Creates new form CrearCounter
     */
    public CrearCounter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreL = new javax.swing.JLabel();
        LCedula = new javax.swing.JLabel();
        LDireccion = new javax.swing.JLabel();
        LCantCasilleros = new javax.swing.JLabel();
        Cnombre = new javax.swing.JTextField();
        CCedula = new javax.swing.JTextField();
        CDireccion = new javax.swing.JTextField();
        CCantCasilleros = new javax.swing.JTextField();
        BCrear = new javax.swing.JButton();
        LTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        NombreL.setText("Nombre del counter");

        LCedula.setText("Cedula Juridica");

        LDireccion.setText("Direccion del counter");

        LCantCasilleros.setText("Cantidad de casilleros a crear ");

        BCrear.setText("Crear");
        BCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCrearActionPerformed(evt);
            }
        });

        LTitulo.setText("Bienvenido nuevo administrado de Counter favor llenar los espacios con lo solicitado ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LDireccion)
                            .addComponent(LCedula)
                            .addComponent(NombreL)
                            .addComponent(LCantCasilleros))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CCantCasilleros)
                            .addComponent(BCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(Cnombre)
                            .addComponent(CCedula)
                            .addComponent(CDireccion)))
                    .addComponent(LTitulo))
                .addGap(0, 186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreL)
                    .addComponent(Cnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCedula)
                    .addComponent(CCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDireccion)
                    .addComponent(CDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCantCasilleros)
                    .addComponent(CCantCasilleros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BCrear)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCrearActionPerformed
       String cantCasilleros = CCantCasilleros.getText();
       String Cedula = CCedula.getText();
       String Direccion = CDireccion.getText();
       String Nombre= Cnombre.getText();
       if (CCantCasilleros.getText().isEmpty()||CCedula.getText().isEmpty()||CDireccion.getText().isEmpty()||Cnombre.getText().isEmpty())
       {
          JOptionPane.showMessageDialog(null, "Tienes que llenar todos los campos para crear la cuenta");    
       }
       else
       {
         try
         {
            int CantCasilleros= Integer.parseInt(CCantCasilleros.getText());
            counter=new Counter(Nombre,Cedula,Direccion,CantCasilleros);
            System.out.println(counter.toString());
            JOptionPane.showMessageDialog(null, 
            "El Counter se ha creado Exitosamente");
            dispose();
         }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La cantidad de casilleros tiene que ser numeros");    
        }
       }

    }//GEN-LAST:event_BCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCounter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCrear;
    private javax.swing.JTextField CCantCasilleros;
    private javax.swing.JTextField CCedula;
    private javax.swing.JTextField CDireccion;
    private javax.swing.JTextField Cnombre;
    private javax.swing.JLabel LCantCasilleros;
    private javax.swing.JLabel LCedula;
    private javax.swing.JLabel LDireccion;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JLabel NombreL;
    // End of variables declaration//GEN-END:variables

}
