/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Cliente;
import Clases.Counter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Chavas
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        Cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BSalir = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        MAdministracion = new javax.swing.JMenu();
        MCounter = new javax.swing.JMenuItem();
        MCuenta = new javax.swing.JMenuItem();
        MEntragables = new javax.swing.JMenu();
        MRecepcion = new javax.swing.JMenuItem();
        MRetiro = new javax.swing.JMenuItem();
        MConsulta = new javax.swing.JMenu();
        MCasilleros = new javax.swing.JMenuItem();
        MRecibidos = new javax.swing.JMenuItem();
        MRetidoD = new javax.swing.JMenuItem();
        MPendientes = new javax.swing.JMenuItem();
        MOtros = new javax.swing.JMenu();
        MDolar = new javax.swing.JMenuItem();
        MPaquetes = new javax.swing.JMenuItem();
        MResumen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        MAdministracion.setText("Administracion");

        MCounter.setText("Counter");
        MCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCounterActionPerformed(evt);
            }
        });
        MAdministracion.add(MCounter);

        MCuenta.setText("Cuentas");
        MCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCuentaActionPerformed(evt);
            }
        });
        MAdministracion.add(MCuenta);

        MenuPrincipal.add(MAdministracion);

        MEntragables.setText("Entregables");

        MRecepcion.setText("Recepcion de articulos");
        MRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRecepcionActionPerformed(evt);
            }
        });
        MEntragables.add(MRecepcion);

        MRetiro.setText("Retiro ");
        MRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRetiroActionPerformed(evt);
            }
        });
        MEntragables.add(MRetiro);

        MConsulta.setText("Consulta");

        MCasilleros.setText("Casilleros");
        MCasilleros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCasillerosActionPerformed(evt);
            }
        });
        MConsulta.add(MCasilleros);

        MRecibidos.setText("Entregable por Fecha");
        MRecibidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRecibidosActionPerformed(evt);
            }
        });
        MConsulta.add(MRecibidos);

        MRetidoD.setText("Retiro Detallado");
        MConsulta.add(MRetidoD);

        MPendientes.setText("Pendientes");
        MConsulta.add(MPendientes);

        MEntragables.add(MConsulta);

        MenuPrincipal.add(MEntragables);

        MOtros.setText("Otros");

        MDolar.setText("Consulta Compra/Venta $");
        MDolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDolarActionPerformed(evt);
            }
        });
        MOtros.add(MDolar);

        MPaquetes.setText("Clientes con paquetes pendientes");
        MPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPaquetesActionPerformed(evt);
            }
        });
        MOtros.add(MPaquetes);

        MResumen.setText("Resumen Contable");
        MResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MResumenActionPerformed(evt);
            }
        });
        MOtros.add(MResumen);

        MenuPrincipal.add(MOtros);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 363, Short.MAX_VALUE)
                .addComponent(BSalir))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 333, Short.MAX_VALUE)
                .addComponent(BSalir))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCuentaActionPerformed
        if(null==CrearCounter.counter)
        {   
            JOptionPane.showMessageDialog(null, "Tienes que crear un counter primero");    
        }
        else
        {
            CreacionCuenta CuentaV =new CreacionCuenta();
            CuentaV.setVisible(true);

        }
    }//GEN-LAST:event_MCuentaActionPerformed

    private void MCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCounterActionPerformed
        CrearCounter CounterV =new CrearCounter();
        CounterV.setVisible(true);   
    }//GEN-LAST:event_MCounterActionPerformed

    private void MPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPaquetesActionPerformed
        Morosos MorososV= new Morosos();
        MorososV.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        MorososV.setVisible(true);
    }//GEN-LAST:event_MPaquetesActionPerformed

    private void MResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MResumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MResumenActionPerformed

    private void MRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRecepcionActionPerformed
        if(null==CrearCounter.counter.NCliente(0))
        {   
            JOptionPane.showMessageDialog(null, "Tienes que tener al menos un cliente");    
        }
        else
        {        
            RecepcionDeEntregables EntregablesV=new RecepcionDeEntregables();
            EntregablesV.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            EntregablesV.setVisible(true);
        }
    }//GEN-LAST:event_MRecepcionActionPerformed

    private void MRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRetiroActionPerformed
        Retiro RetiroV= new Retiro();
        RetiroV.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        RetiroV.setVisible(true);
      
        
    }//GEN-LAST:event_MRetiroActionPerformed

    private void MCasillerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCasillerosActionPerformed
    Consultacasilleros CasilleroV=new Consultacasilleros();
    CasilleroV.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    CasilleroV.setVisible(true);
    }//GEN-LAST:event_MCasillerosActionPerformed

    private void MRecibidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRecibidosActionPerformed
    BusquedaEntregables EntregablesV=new BusquedaEntregables();
    EntregablesV.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    EntregablesV.setVisible(true);
    }//GEN-LAST:event_MRecibidosActionPerformed

    private void MDolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDolarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MDolarActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
    dispose();
    }//GEN-LAST:event_BSalirActionPerformed

    private void Cargar(){
    CrearCounter.counter=new Counter("primero","12345","Por ahi",5);
    Cliente Cuenta=new Cliente("Oscar","Ch.","1000k", "ocach14@hotmail.com","56262","Por ahi", "Hombre","1/14/20","Normal");
    CrearCounter.counter.AgregarClientes(Cuenta);
    Cliente Cuenta2=new Cliente("felo","Ch.","1020k", "ocach14@hotmail.com","56262","Por ahi", "Hombre","1/14/20","Plata");
    CrearCounter.counter.AgregarClientes(Cuenta2);
    Cliente Cuenta3=new Cliente("otto","Ch.","1100k", "ocach14@hotmail.com","56262","Por ahi", "Hombre","1/14/20","Oro");
    CrearCounter.counter.AgregarClientes(Cuenta3);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSalir;
    private javax.swing.JMenu MAdministracion;
    private javax.swing.JMenuItem MCasilleros;
    private javax.swing.JMenu MConsulta;
    private javax.swing.JMenuItem MCounter;
    private javax.swing.JMenuItem MCuenta;
    private javax.swing.JMenuItem MDolar;
    private javax.swing.JMenu MEntragables;
    private javax.swing.JMenu MOtros;
    private javax.swing.JMenuItem MPaquetes;
    private javax.swing.JMenuItem MPendientes;
    private javax.swing.JMenuItem MRecepcion;
    private javax.swing.JMenuItem MRecibidos;
    private javax.swing.JMenuItem MResumen;
    private javax.swing.JMenuItem MRetidoD;
    private javax.swing.JMenuItem MRetiro;
    private javax.swing.JMenuBar MenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
