/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Cancelar;
import Clases.Paquete;
import Clases.Revista;
import Clases.Sobre;
import WEBSERVICE.Webservice;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chavas
 */
public class Pagar extends javax.swing.JFrame {

    /**
     * Creates new form Pagar
     */
    public Pagar() {
        initComponents();
        CargarPendientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollTable = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        LMonto$ = new javax.swing.JLabel();
        LMonto₡ = new javax.swing.JLabel();
        LDeudaTotal$ = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CKTarjetas = new javax.swing.JCheckBox();
        CKContado = new javax.swing.JCheckBox();
        Tarjetas = new javax.swing.JComboBox();
        BPagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LCambio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollTable.setViewportView(Table);

        LDeudaTotal$.setText("Deuda Total $");

        jLabel1.setText("Deuda Total ₡ ");

        jLabel3.setText("Tipo de paga");

        CKTarjetas.setText("Tarjeta");
        CKTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CKTarjetasActionPerformed(evt);
            }
        });

        CKContado.setText("De Contado");
        CKContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CKContadoActionPerformed(evt);
            }
        });

        Tarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetasActionPerformed(evt);
            }
        });

        BPagar.setText("Pagar");
        BPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPagarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nota:Tipo de Cambio ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LDeudaTotal$, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LMonto$, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LMonto₡, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Tarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(CKTarjetas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CKContado))))))
                .addGap(0, 144, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(BPagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ScrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LDeudaTotal$, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(LMonto$, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LMonto₡, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CKTarjetas)
                    .addComponent(CKContado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TarjetasActionPerformed

    private void CKContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CKContadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CKContadoActionPerformed

    private void CKTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CKTarjetasActionPerformed

        Tarjetas.addItem("VISA");
        Tarjetas.addItem("MASTER CARD");
        Tarjetas.addItem("AMERICAN EXPRESS");

    }//GEN-LAST:event_CKTarjetasActionPerformed

    private void BPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPagarActionPerformed
    for (int i = 0; i < Cancelar.Pagar.size(); i++)
    {   
        Cancelar.Pagar.get(i).setEstregado(true);
        Date date = new Date();
        Cancelar.Pagar.get(i).setFechaE(date);
        Retiro.cliente.addPago();
        dispose();
    }
        Retiro.cliente.Actualizarnivel();
    }//GEN-LAST:event_BPagarActionPerformed
    public  void CargarPendientes() {
        double DeudaTotal=0;
        JTable table=new JTable();
        String encabezados[] = {"Tipo","Identificador","Deuda"};
        DefaultTableModel dtm = new DefaultTableModel(encabezados, Cancelar.Pagar.size());
        for (int i = 0; i < Cancelar.Pagar.size(); i++)
        {
            int DuedaPer=0;
            if(Cancelar.Pagar.get(i) instanceof Sobre )
            {
                if ("Documentacion".equals(((Sobre)Cancelar.Pagar.get(i)).getContenido()))            
                {
                    if ("Manila".equals(((Sobre)Cancelar.Pagar.get(i)).getTipo())){DuedaPer++;}        
                }
                else
                {
                    if ("Manila".equals(((Sobre)Cancelar.Pagar.get(i)).getTipo())){DuedaPer=2;} 
                    else{DuedaPer++;}                      
                }
                dtm.setValueAt("Sobre", i, 0);
                dtm.setValueAt(Cancelar.Pagar.get(i).getIdentificador(), i, 1);
                dtm.setValueAt(DuedaPer, i, 2);   
                DeudaTotal+=DuedaPer;
            }
            else
            {
                if(Cancelar.Pagar.get(i) instanceof Revista )
                {
                    if(!((Revista)Cancelar.Pagar.get(i)).isCatalogo()){DuedaPer++;}
                    dtm.setValueAt("Revista", i, 0);
                    dtm.setValueAt(Cancelar.Pagar.get(i).getIdentificador(), i, 1);
                    dtm.setValueAt(DuedaPer, i, 2);   
                    DeudaTotal+=DuedaPer;
                        
                }
                else
                {
                    if ( Cancelar.Pagar.get(i) instanceof Paquete)
                    {   
                        DuedaPer+=(((Paquete)Cancelar.Pagar.get(i)).getPeso())*0.02;
                        if (((Paquete)Cancelar.Pagar.get(i)).isElectronico()&&((Paquete)Cancelar.Pagar.get(i)).isFragil())
                        {
                            DuedaPer+=4;
                        }
                        else
                        {
                            if (((Paquete)Cancelar.Pagar.get(i)).isElectronico()||((Paquete)Cancelar.Pagar.get(i)).isFragil())
                            {
                                DuedaPer+=2;
                            }
                        }
                        dtm.setValueAt("Paquete", i, 0);
                        dtm.setValueAt(Cancelar.Pagar.get(i).getIdentificador(), i, 1);
                        dtm.setValueAt(DuedaPer, i, 2);   
                        DeudaTotal+=DuedaPer;

                    }
                }
            }
        }
        String Nivel= Retiro.cliente.getNivel();
        double Descuento=0;
        
        if (Nivel=="Plata")
        {
             Descuento = (double)(DeudaTotal*(5.0f/100.0f));
        }
        else
        {
            if(Nivel=="Oro")
            {
              Descuento = (double)(DeudaTotal*(10.0f/100.0f));
              System.out.println(Descuento);
            }
        }
        DeudaTotal=DeudaTotal-Descuento;
        
        Table.setModel(dtm);
        String Colon=Webservice.ValorDolar();
        setLCambio(Colon);
        double Colones = Double.parseDouble(Colon);
        double DColon=Colones*DeudaTotal;
        String Dueda = Double.toString(DeudaTotal);
        String DColones=Double.toString((double) DColon);
        setDuedaTotal(Dueda);
        setLMonto₡(DColones);
    }//Fin del metodo cargaEstudiantes
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPagar;
    private javax.swing.JCheckBox CKContado;
    private javax.swing.JCheckBox CKTarjetas;
    private javax.swing.JLabel LCambio;
    private javax.swing.JLabel LDeudaTotal$;
    private javax.swing.JLabel LMonto$;
    private javax.swing.JLabel LMonto₡;
    private javax.swing.JScrollPane ScrollTable;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox Tarjetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void setDuedaTotal(String  DuedaTotal) {
        this.LMonto$.setText(DuedaTotal);
    }

    public void setTable(JTable Table) {
        this.Table = Table;
    }

    public void setTarjetas(JComboBox jComboBox1) {
        this.Tarjetas = jComboBox1;
    }

    public void setLMonto₡(String LMonto₡) {
        this.LMonto₡.setText(LMonto₡);
    }

    public void setLCambio(String LCambio) {
        this.LCambio.setText(LCambio);
    }

}
