/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Paquete;
import Clases.Revista;
import Clases.Sobre;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Chavas
 */
public class RecepcionDeEntregables extends javax.swing.JFrame {

    /**
     * Creates new form RecepcionDeEntregables
     */
    public RecepcionDeEntregables() {
        initComponents();
        setCBRemitente();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prestañas = new javax.swing.JTabbedPane();
        PRevista = new javax.swing.JPanel();
        LTituloR = new javax.swing.JLabel();
        LNombreR = new javax.swing.JLabel();
        LCatalogoR = new javax.swing.JLabel();
        LTemaR = new javax.swing.JLabel();
        LDescripcionR = new javax.swing.JLabel();
        CBCatalogoR = new javax.swing.JComboBox();
        CBTemaR = new javax.swing.JComboBox();
        CNombreR = new javax.swing.JTextField();
        CDescripcionR = new javax.swing.JTextField();
        BCrearR = new javax.swing.JButton();
        CBRemitente1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PSobre = new javax.swing.JPanel();
        LTituloS = new javax.swing.JLabel();
        LTipoS = new javax.swing.JLabel();
        LContenidoS = new javax.swing.JLabel();
        LPesoS = new javax.swing.JLabel();
        LDescripcionS = new javax.swing.JLabel();
        CBTipoS = new javax.swing.JComboBox();
        CBContenidoS = new javax.swing.JComboBox();
        CBRemitente = new javax.swing.JComboBox();
        CPesoS = new javax.swing.JTextField();
        CDescripcionS = new javax.swing.JTextField();
        BCrearS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        PPaquete = new javax.swing.JPanel();
        LTituloP = new javax.swing.JLabel();
        LEvolturaP = new javax.swing.JLabel();
        LElectronicoP = new javax.swing.JLabel();
        LFragilP = new javax.swing.JLabel();
        LPesoP = new javax.swing.JLabel();
        LDescripcionP = new javax.swing.JLabel();
        CBEnvolturaP = new javax.swing.JComboBox();
        CBElectronicoP = new javax.swing.JComboBox();
        CBFragilP = new javax.swing.JComboBox();
        CPesoP = new javax.swing.JTextField();
        CDescripcionP = new javax.swing.JTextField();
        BCrearP = new javax.swing.JButton();
        CBRemitente2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LTituloR.setText("Llene lo solicitado en base a la revista");

        LNombreR.setText("Nombre");

        LCatalogoR.setText("Catalogo?");

        LTemaR.setText("Tema");

        LDescripcionR.setText("Descripcion");

        CBCatalogoR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));

        CBTemaR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Negocios", "Moda/Belleza", "Tecnología", "Salud/Medicina", "Cocina u Otro" }));
        CBTemaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTemaRActionPerformed(evt);
            }
        });

        CDescripcionR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDescripcionRActionPerformed(evt);
            }
        });

        BCrearR.setText("Crear");
        BCrearR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCrearRActionPerformed(evt);
            }
        });

        CBRemitente.setSelectedItem("text has changed");
        CBRemitente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBRemitente1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Remitente");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PRevistaLayout = new javax.swing.GroupLayout(PRevista);
        PRevista.setLayout(PRevistaLayout);
        PRevistaLayout.setHorizontalGroup(
            PRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRevistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LTituloR)
                    .addComponent(LDescripcionR)
                    .addGroup(PRevistaLayout.createSequentialGroup()
                        .addGroup(PRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LCatalogoR)
                            .addComponent(LTemaR)
                            .addComponent(LNombreR)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(PRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PRevistaLayout.createSequentialGroup()
                                .addComponent(CBRemitente1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(CBTemaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBCatalogoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BCrearR)
                            .addComponent(CDescripcionR)
                            .addComponent(CNombreR))))
                .addGap(187, 187, 187))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PRevistaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        PRevistaLayout.setVerticalGroup(
            PRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRevistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LTituloR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNombreR)
                    .addComponent(CNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCatalogoR)
                    .addComponent(CBCatalogoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTemaR)
                    .addComponent(CBTemaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDescripcionR)
                    .addComponent(CDescripcionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBRemitente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BCrearR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        Prestañas.addTab("Revistas", PRevista);

        LTituloS.setText("Llene los datos solicitados en base al sobre");

        LTipoS.setText("Tipo");

        LContenidoS.setText("Contenido");

        LPesoS.setText("Peso(Kg)");

        LDescripcionS.setText("Descripcion");

        CBTipoS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aero", "Manila" }));
        CBTipoS.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                CBTipoSComponentRemoved(evt);
            }
        });
        CBTipoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTipoSActionPerformed(evt);
            }
        });

        CBContenidoS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Documentacion", "Otros" }));
        CBContenidoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBContenidoSActionPerformed(evt);
            }
        });

        CBRemitente.setSelectedItem("text has changed");
        CBRemitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBRemitenteActionPerformed(evt);
            }
        });

        CDescripcionS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDescripcionSActionPerformed(evt);
            }
        });

        BCrearS.setText("Crear");
        BCrearS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCrearSActionPerformed(evt);
            }
        });

        jLabel1.setText("Remitente");

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PSobreLayout = new javax.swing.GroupLayout(PSobre);
        PSobre.setLayout(PSobreLayout);
        PSobreLayout.setHorizontalGroup(
            PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PSobreLayout.createSequentialGroup()
                .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PSobreLayout.createSequentialGroup()
                        .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LTipoS)
                            .addComponent(LContenidoS))
                        .addGap(23, 23, 23)
                        .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBContenidoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBTipoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LTituloS)
                    .addGroup(PSobreLayout.createSequentialGroup()
                        .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LPesoS)
                            .addComponent(LDescripcionS)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CDescripcionS)
                            .addGroup(PSobreLayout.createSequentialGroup()
                                .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CPesoS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BCrearS)
                                    .addComponent(CBRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(0, 172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PSobreLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        PSobreLayout.setVerticalGroup(
            PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PSobreLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LTituloS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTipoS)
                    .addComponent(CBTipoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LContenidoS)
                    .addComponent(CBContenidoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LPesoS)
                    .addGroup(PSobreLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CPesoS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDescripcionS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LDescripcionS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BCrearS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        Prestañas.addTab("Sobres", PSobre);

        LTituloP.setText("Llene lo solicitado en base al paquete");

        LEvolturaP.setText("Envoltura");

        LElectronicoP.setText("Electronico?");

        LFragilP.setText("Fragil?");

        LPesoP.setText("Peso(Kg)");

        LDescripcionP.setText("Descripcion");

        CBEnvolturaP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bolsa", "Caja" }));
        CBEnvolturaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEnvolturaPActionPerformed(evt);
            }
        });

        CBElectronicoP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));
        CBElectronicoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBElectronicoPActionPerformed(evt);
            }
        });

        CBFragilP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));
        CBFragilP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFragilPActionPerformed(evt);
            }
        });

        CPesoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPesoPActionPerformed(evt);
            }
        });

        BCrearP.setText("Crear");
        BCrearP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCrearPActionPerformed(evt);
            }
        });

        CBRemitente.setSelectedItem("text has changed");
        CBRemitente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBRemitente2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Remitente");

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PPaqueteLayout = new javax.swing.GroupLayout(PPaquete);
        PPaquete.setLayout(PPaqueteLayout);
        PPaqueteLayout.setHorizontalGroup(
            PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPaqueteLayout.createSequentialGroup()
                .addGroup(PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LFragilP)
                    .addComponent(LPesoP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PPaqueteLayout.createSequentialGroup()
                .addGroup(PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LTituloP)
                    .addGroup(PPaqueteLayout.createSequentialGroup()
                        .addGroup(PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LDescripcionP)
                            .addComponent(LElectronicoP)
                            .addComponent(LEvolturaP)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBEnvolturaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBElectronicoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BCrearP)
                            .addComponent(CPesoP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBFragilP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CDescripcionP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBRemitente2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPaqueteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        PPaqueteLayout.setVerticalGroup(
            PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPaqueteLayout.createSequentialGroup()
                .addGroup(PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PPaqueteLayout.createSequentialGroup()
                        .addComponent(LTituloP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LEvolturaP)
                            .addComponent(CBEnvolturaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LElectronicoP, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBElectronicoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LFragilP)
                            .addComponent(CBFragilP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LPesoP)
                            .addComponent(CPesoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LDescripcionP)
                            .addComponent(CDescripcionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBRemitente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BCrearP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        Prestañas.addTab("Paquetes", PPaquete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Prestañas, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Prestañas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBEnvolturaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEnvolturaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBEnvolturaPActionPerformed

    private void BCrearPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCrearPActionPerformed
    String Envoltura = CBEnvolturaP.getSelectedItem().toString();
    String electronico= CBElectronicoP.getSelectedItem().toString();
    boolean Electronico=false;
    if("Si".equals(electronico)){
        Electronico=true;
    }
    String fragil = CBFragilP.getSelectedItem().toString();
    boolean Fragil=false;
    
    if("Si".equals(fragil)){
       Fragil=true;
    }
    int Peso=0;
    if (CDescripcionP.getText().isEmpty()||CPesoP.getText().isEmpty())
       {
          JOptionPane.showMessageDialog(null, "Tienes que llenar todos los campos para crear la cuenta");    
       }
    else
    {
        try
        {
            
            Peso= Integer.parseInt(CPesoP.getText());
            String Descripcion=CDescripcionP.getText();
            String Remitente= CBRemitente2.getSelectedItem().toString();
            
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            //get current date time with Date()
            Date date = new Date();
            System.out.println(dateFormat.format(date));
            
            
            Paquete paquete = new Paquete(Envoltura,Electronico,Fragil,Peso,Identificador(),false,Descripcion,Remitente,date);
            CrearCounter.counter.AgregarEntregables(paquete);
            System.out.println(paquete.toString());
            
        }                                       
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El peso tiene que ser numeros");    
        }
    
    }

    
    }//GEN-LAST:event_BCrearPActionPerformed

    private void CBTipoSComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_CBTipoSComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTipoSComponentRemoved

    private void CBTipoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTipoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTipoSActionPerformed

    private void BCrearSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCrearSActionPerformed
    String tipo= CBTipoS.getSelectedItem().toString();
    String Contenido= CBContenidoS.getSelectedItem().toString();
    String Descripcion=CDescripcionS.getText();
    String Remitente= CBRemitente.getSelectedItem().toString();
    int Peso=0;
     if (CDescripcionS.getText().isEmpty()||CPesoS.getText().isEmpty())
       {
          JOptionPane.showMessageDialog(null, "Tienes que llenar todos los campos para crear la cuenta");    
       }
     else
     {     
        try
         {
             Peso= Integer.parseInt(CPesoS.getText());
             
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            //get current date time with Date()
            Date date = new Date();
            System.out.println(dateFormat.format(date));
            
            
            Sobre sobre= new Sobre(tipo,Contenido,Peso,Identificador(),false,Descripcion,Remitente,date);
            CrearCounter.counter.AgregarEntregables(sobre);
            System.out.println(sobre.toString());
         }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El peso tiene que ser numeros");    
        }

    }
    }//GEN-LAST:event_BCrearSActionPerformed

    private void CBContenidoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBContenidoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBContenidoSActionPerformed

    private void CBElectronicoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBElectronicoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBElectronicoPActionPerformed

    private void CBFragilPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFragilPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBFragilPActionPerformed

    private void CPesoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPesoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPesoPActionPerformed

    private void CDescripcionSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDescripcionSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDescripcionSActionPerformed

    private void BCrearRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCrearRActionPerformed
    
    String Nombre = CNombreR.getText();
    String catalogo= CBCatalogoR.getSelectedItem().toString();
    String Remitente= CBRemitente1.getSelectedItem().toString();
    boolean Catalogo=false;
    if("Si".equals(catalogo)){
        Catalogo=true;
    }
    if (CDescripcionR.getText().isEmpty()||CNombreR.getText().isEmpty())
    {
          JOptionPane.showMessageDialog(null, "Tienes que llenar todos los campos para crear la cuenta");    
    }
    else
    {
        String Tema= CBTemaR.getSelectedItem().toString();
        String Descripcion=CDescripcionR.getText();
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        //get current date time with Date()
        Date date = new Date();
        System.out.println(dateFormat.format(date));
            
        Revista revista = new Revista(Nombre,Catalogo,Tema,Identificador(),false,Descripcion,Remitente,date);
        CrearCounter.counter.AgregarEntregables(revista);
        System.out.println(revista.toString());
    }
    
    }//GEN-LAST:event_BCrearRActionPerformed

    private void CBTemaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTemaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTemaRActionPerformed

    private void CDescripcionRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDescripcionRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDescripcionRActionPerformed

    private void CBRemitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBRemitenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBRemitenteActionPerformed

    private void CBRemitente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBRemitente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBRemitente1ActionPerformed

    private void CBRemitente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBRemitente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBRemitente2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
private String Identificador()
{
        int pos;
        pos = new Random().nextInt(26);
        numero=numero+pos;
        StringBuilder sb = new StringBuilder();
        sb.append("");
        sb.append(numero);
        String Numero = sb.toString();
        String Identificador ;
        char letra=letras.charAt( pos );
        Identificador = letra+Numero;
        return Identificador;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecepcionDeEntregables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecepcionDeEntregables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecepcionDeEntregables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecepcionDeEntregables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecepcionDeEntregables().setVisible(true);
                
            }
        });
    }
    public final String letras="adbcefghijklmnopqrestuvwxyz"; 
    public int numero=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCrearP;
    private javax.swing.JButton BCrearR;
    private javax.swing.JButton BCrearS;
    private javax.swing.JComboBox CBCatalogoR;
    private javax.swing.JComboBox CBContenidoS;
    private javax.swing.JComboBox CBElectronicoP;
    private javax.swing.JComboBox CBEnvolturaP;
    private javax.swing.JComboBox CBFragilP;
    private javax.swing.JComboBox CBRemitente;
    private javax.swing.JComboBox CBRemitente1;
    private javax.swing.JComboBox CBRemitente2;
    private javax.swing.JComboBox CBTemaR;
    private javax.swing.JComboBox CBTipoS;
    private javax.swing.JTextField CDescripcionP;
    private javax.swing.JTextField CDescripcionR;
    private javax.swing.JTextField CDescripcionS;
    private javax.swing.JTextField CNombreR;
    private javax.swing.JTextField CPesoP;
    private javax.swing.JTextField CPesoS;
    private javax.swing.JLabel LCatalogoR;
    private javax.swing.JLabel LContenidoS;
    private javax.swing.JLabel LDescripcionP;
    private javax.swing.JLabel LDescripcionR;
    private javax.swing.JLabel LDescripcionS;
    private javax.swing.JLabel LElectronicoP;
    private javax.swing.JLabel LEvolturaP;
    private javax.swing.JLabel LFragilP;
    private javax.swing.JLabel LNombreR;
    private javax.swing.JLabel LPesoP;
    private javax.swing.JLabel LPesoS;
    private javax.swing.JLabel LTemaR;
    private javax.swing.JLabel LTipoS;
    private javax.swing.JLabel LTituloP;
    private javax.swing.JLabel LTituloR;
    private javax.swing.JLabel LTituloS;
    private javax.swing.JPanel PPaquete;
    private javax.swing.JPanel PRevista;
    private javax.swing.JPanel PSobre;
    private javax.swing.JTabbedPane Prestañas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void setCBRemitente() {
        int pos=0;
        String Nombre="";
        while (Nombre!=null)
        {
            Nombre=CrearCounter.counter.NCliente(pos);
            if (Nombre!=null)
            {
            CBRemitente.addItem(Nombre);
            CBRemitente1.addItem(Nombre);
            CBRemitente2.addItem(Nombre);
            pos+=1;
            }
        }
    }
}