/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Gollo
 */
public class FInformacion extends javax.swing.JFrame {

    /**
     * Creates new form FInformacion
     */
    public FInformacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnGraphicoP = new javax.swing.JPanel();
        BGrapP = new javax.swing.JButton();
        PnGraphicoC = new javax.swing.JPanel();
        BGrCur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PnGraphicoPLayout = new javax.swing.GroupLayout(PnGraphicoP);
        PnGraphicoP.setLayout(PnGraphicoPLayout);
        PnGraphicoPLayout.setHorizontalGroup(
            PnGraphicoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        PnGraphicoPLayout.setVerticalGroup(
            PnGraphicoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        BGrapP.setText("Top 3 Profesores");
        BGrapP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrapPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnGraphicoCLayout = new javax.swing.GroupLayout(PnGraphicoC);
        PnGraphicoC.setLayout(PnGraphicoCLayout);
        PnGraphicoCLayout.setHorizontalGroup(
            PnGraphicoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        PnGraphicoCLayout.setVerticalGroup(
            PnGraphicoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        BGrCur.setText("Top 5 Cursos");
        BGrCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrCurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(BGrapP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BGrCur)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnGraphicoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(PnGraphicoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BGrapP)
                    .addComponent(BGrCur))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PnGraphicoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnGraphicoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGrapPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrapPActionPerformed
        CrearGraficoCircular(0,"");
    }//GEN-LAST:event_BGrapPActionPerformed

    private void BGrCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrCurActionPerformed
        CrearGraficoCircular(1,"");
    }//GEN-LAST:event_BGrCurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FInformacion().setVisible(true);
            }
        });
    }
      private  void CrearGraficoCircular(int TipoG, String DatosP) { 
        if(TipoG==0)
        {
            BufferedImage _image;//para la imagen en memoria
            JFreeChart grafico;// el grafico
            Dimension d = PnGraphicoP.getSize();
            DefaultPieDataset dataset = new DefaultPieDataset();

            // Establecemos unas categorías de ejemplo
            dataset.setValue("Profesor1", 2);
            dataset.setValue("Profesor2", 3);
            dataset.setValue("Profesor3", 5);

            // Creamos la tabla
            grafico = ChartFactory.createPieChart(
                    "Top 3 Profesores",
                    dataset,
                    true,
                    true,
                    false);
            JLabel j = new JLabel();
            j.setBounds(0, 0, d.width, d.height);

            _image = grafico.createBufferedImage(d.width, d.height);
            ImageIcon imagenFondo = new ImageIcon(_image);
            j.setIcon(imagenFondo);
            j.repaint();

            PnGraphicoP.add(j);
            PnGraphicoP.setVisible(true);

            this.add(PnGraphicoP);
            this.repaint();
        }
        else{
            
            BufferedImage _image;//para la imagen en memoria
            JFreeChart grafico;// el grafico
            Dimension d = PnGraphicoC.getSize();
            DefaultPieDataset dataset = new DefaultPieDataset();

            // Establecemos unas categorías de ejemplo
            dataset.setValue("Curso1", 2);
            dataset.setValue("Curso2", 3);
            dataset.setValue("Curso3", 7);
            dataset.setValue("Curso4", 9);
            dataset.setValue("Curso5", 4);
            // Creamos la tabla
            grafico = ChartFactory.createPieChart(
                    "Top 5 Cursos",
                    dataset,
                    true,
                    true,
                    false);
            JLabel j = new JLabel();
            j.setBounds(0, 0, d.width, d.height);

            _image = grafico.createBufferedImage(d.width, d.height);
            ImageIcon imagenFondo = new ImageIcon(_image);
            j.setIcon(imagenFondo);
            j.repaint();

            PnGraphicoC.add(j);
            PnGraphicoC.setVisible(true);

            this.add(PnGraphicoC);
            this.repaint();

        }
        
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGrCur;
    private javax.swing.JButton BGrapP;
    private javax.swing.JPanel PnGraphicoC;
    private javax.swing.JPanel PnGraphicoP;
    // End of variables declaration//GEN-END:variables
}
