/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;


import Clases.Graficas;
import Clases.Servidor;
import Clases.Ticket;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;



/**
 *
 * @author Chavas
 */
public class Administrador extends javax.swing.JFrame {

    private final String HOST = "localhost";
    private final int PUERTO= 5000;
    static public Servidor Server;
    

    public void setTiempoTE(JTextField TiempoTE) {
        this.TiempoTE = TiempoTE;
    }

    public JTextField getTiempoTE() {
        return TiempoTE;
    }

    public JTextField getNombreUsuario() {
        return NombreUsuario;
    }

    public void setNombreUsuario(JTextField NombreUsuario) {
        this.NombreUsuario = NombreUsuario;
    }
    
    
    Graficas migrafico = new Graficas();
    private BufferedImage _image;//para la imagen en memoria
    private JFreeChart grafico;// el grafico
    ArrayList<Ticket>TP=new ArrayList<Ticket>();
    


    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PAdministrador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BCargarTickets = new javax.swing.JButton();
        BAsignarCategoria = new javax.swing.JButton();
        BLevantarServidor = new javax.swing.JButton();
        BBajarServer = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PTexto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TMonitoreo = new javax.swing.JTextArea();
        PGrafico = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableTickFech = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableTickFechXU = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TiempoTE = new javax.swing.JTextField();

        setTitle("Admin");
        setForeground(new java.awt.Color(255, 255, 255));

        PAdministrador.setLayout(null);

        jLabel1.setText("Bienvenido Administrador");
        PAdministrador.add(jLabel1);
        jLabel1.setBounds(189, 11, 154, 14);

        jLabel2.setText("Que deseas hacer?");
        PAdministrador.add(jLabel2);
        jLabel2.setBounds(189, 36, 130, 17);

        BCargarTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/load.png"))); // NOI18N
        BCargarTickets.setText("CargarTickets");
        BCargarTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarTicketsActionPerformed(evt);
            }
        });
        PAdministrador.add(BCargarTickets);
        BCargarTickets.setBounds(153, 63, 181, 41);

        BAsignarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Select.png"))); // NOI18N
        BAsignarCategoria.setText("Asignar Categorias");
        BAsignarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAsignarCategoriaActionPerformed(evt);
            }
        });
        PAdministrador.add(BAsignarCategoria);
        BAsignarCategoria.setBounds(153, 110, 181, 41);

        BLevantarServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/upload.png"))); // NOI18N
        BLevantarServidor.setText("Subir Servidor");
        BLevantarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLevantarServidorActionPerformed(evt);
            }
        });
        PAdministrador.add(BLevantarServidor);
        BLevantarServidor.setBounds(153, 157, 181, 41);

        BBajarServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download.png"))); // NOI18N
        BBajarServer.setText("Bajar Servidor");
        BBajarServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBajarServerActionPerformed(evt);
            }
        });
        PAdministrador.add(BBajarServer);
        BBajarServer.setBounds(153, 204, 181, 46);

        jButton6.setText("Salir ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PAdministrador.add(jButton6);
        jButton6.setBounds(475, 438, 70, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/servidor-computacional-de-la-nube-del-tacto-del-hombre-de-negocios-para-el-servicio-de-lanzamiento-33805644.jpg"))); // NOI18N
        PAdministrador.add(jLabel3);
        jLabel3.setBounds(-550, 0, 1110, 470);

        jTabbedPane1.addTab("Administrador", PAdministrador);

        PTexto.setBackground(new java.awt.Color(0, 0, 153));

        TMonitoreo.setBackground(new java.awt.Color(0, 0, 0));
        TMonitoreo.setColumns(20);
        TMonitoreo.setForeground(new java.awt.Color(255, 255, 0));
        TMonitoreo.setRows(5);
        jScrollPane1.setViewportView(TMonitoreo);

        javax.swing.GroupLayout PGraficoLayout = new javax.swing.GroupLayout(PGrafico);
        PGrafico.setLayout(PGraficoLayout);
        PGraficoLayout.setHorizontalGroup(
            PGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PGraficoLayout.setVerticalGroup(
            PGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Ver grafico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PTextoLayout = new javax.swing.GroupLayout(PTexto);
        PTexto.setLayout(PTextoLayout);
        PTextoLayout.setHorizontalGroup(
            PTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTextoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTextoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTextoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        PTextoLayout.setVerticalGroup(
            PTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
            .addGroup(PTextoLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(PGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver Servidor", PTexto);

        jButton2.setText("Las consultas en el servidor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TableTickFech.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableTickFech.setToolTipText("");
        TableTickFech.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(TableTickFech);

        TableTickFechXU.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableTickFechXU.setToolTipText("");
        TableTickFechXU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(TableTickFechXU);

        jLabel4.setText("Nombre del usuario");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());

        jSpinner2.setModel(new javax.swing.SpinnerDateModel());

        jLabel5.setText("Desde");

        jLabel6.setText("Hasta");

        jLabel7.setText("Tiempo de ticket por cliente:");

        TiempoTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoTEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TiempoTE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TiempoTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Las consultas al servidor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void BAsignarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAsignarCategoriaActionPerformed
        if (Server == null)
        {
            
            JOptionPane.showMessageDialog(null, "Servidor Apagado");
        }
        else
        {
            if (Server.getInbox().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Noy hay tickets Cargados");
            } else {
                AsignarCategorias CategoriasV = new AsignarCategorias();
                CategoriasV.setVisible(true);

            }
        }
        
    }//GEN-LAST:event_BAsignarCategoriaActionPerformed

    private void BLevantarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLevantarServidorActionPerformed

        if (Server == null) {

            Server = new Servidor();
            Server.start();
        } else {
            JOptionPane.showMessageDialog(null, "El servidor ya ha sido subido");
        }
    }//GEN-LAST:event_BLevantarServidorActionPerformed

    private void BCargarTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarTicketsActionPerformed
 
        if (Server == null) {
            JOptionPane.showMessageDialog(null, "Servidor apagado");
            
        } else {
            Server.CargarXls();
        }

    }//GEN-LAST:event_BCargarTicketsActionPerformed

    private void BBajarServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBajarServerActionPerformed
        Server.BajarServidor();
    }//GEN-LAST:event_BBajarServerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    CrearGraficoCircular();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Server.TiempoPorTiquet();
        TiempoTE.setText( Integer.toString(Server.getTT()));
        createJlist();
        createJlist2();
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TiempoTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoTEActionPerformed
    public static void Monitoreo(String datos) 
    {
        TMonitoreo.append(datos);
            
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
        
    }
    
    
       public void createJlist() {
        DefaultListModel listModel = new DefaultListModel();    
        int i;
        
        TP=Server.getTicketsProcesados();
       System.out.println(TP.size());
        for (i = 0; i < TP.size(); i++) {
            System.out.println(TP.get(i).getEstado());
            if("Atendido".equals(TP.get(i).getEstado()))
            {
                System.out.println("si entro");
                String Dato = "Fecha de Recepcion: ";
                Dato += TP.get(i).getRecepcion() + "  ";
                Dato += "ID Cliente: " + TP.get(i).getID_Cliente() + "  ";
                Dato += "Asunto: " + TP.get(i).getAsunto() + "  ";
                Dato += "Categoria: " + TP.get(i).getCategoria() + "  ";
                Dato += "Estado: " + TP.get(i).getEstado()+ "  ";
                
                listModel.addElement(Dato);
            }
        }

        TableTickFech.setModel( listModel);

    } 
       public void createJlist2() {
        DefaultListModel listModel1 = new DefaultListModel();    
        int i;
        
        TP=Server.getTicketsProcesados();
       System.out.println(TP.size());
        for (i = 0; i < TP.size(); i++) {
            System.out.println(NombreUsuario.getText());
            if("Atendido".equals(TP.get(i).getEstado()) && NombreUsuario.getText().equalsIgnoreCase(TP.get(i).getID_Empleado()))
            {
                System.out.println("si entro");
                String Dato = "Fecha de Recepcion: ";
                Dato += TP.get(i).getRecepcion() + "  ";
                Dato += "ID Cliente: " + TP.get(i).getID_Cliente() + "  ";
                Dato += "Asunto: " + TP.get(i).getAsunto() + "  ";
                Dato += "Categoria: " + TP.get(i).getCategoria() + "  ";
                Dato += "Estado: " + TP.get(i).getEstado()+ "  ";
                
                listModel1.addElement(Dato);
            }
        }

        TableTickFechXU.setModel( listModel1);

    } 
    private void CrearGraficoCircular() {                                         
        Dimension d = PGrafico.getSize();
        DefaultPieDataset dataset = new DefaultPieDataset();

        // Establecemos unas categorías de ejemplo
        dataset.setValue("ColaRoja", 2);
        dataset.setValue("ColaAmarilla", 3);
        dataset.setValue("ColaVerde", Server.getLargo_ColaVerde());

        // Creamos la tabla
        grafico = ChartFactory.createPieChart(
                "Colas",
                dataset,
                true,
                true,
                false);
        JLabel j = new JLabel();
        j.setBounds(0, 0, d.width, d.height);

        _image = grafico.createBufferedImage(d.width, d.height);
        ImageIcon imagenFondo = new ImageIcon(_image);
        j.setIcon(imagenFondo);
        j.repaint();

        PGrafico.add(j);
        this.repaint();
    }                                        

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAsignarCategoria;
    private javax.swing.JButton BBajarServer;
    private javax.swing.JButton BCargarTickets;
    private javax.swing.JButton BLevantarServidor;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JPanel PAdministrador;
    private javax.swing.JPanel PGrafico;
    private javax.swing.JPanel PTexto;
    public static javax.swing.JTextArea TMonitoreo;
    private javax.swing.JList TableTickFech;
    private javax.swing.JList TableTickFechXU;
    private javax.swing.JTextField TiempoTE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
