/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Empleado;
import Frames.Administrador;
import Frames.EmpleadoF;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Chavas
 */
public class Login extends javax.swing.JFrame {
        ArrayList<Empleado> Empleados=new ArrayList<Empleado>();
        Empleado Admin=new Empleado("Administrador","12345","admin");
            
        static Empleado EmpleadoLogeado;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        AgregarEmpleados();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CID = new javax.swing.JTextField();
        CContraseña = new javax.swing.JPasswordField();
        BLogin = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        LContraseña = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 250));
        setMaximumSize(new java.awt.Dimension(356, 294));
        setMinimumSize(new java.awt.Dimension(356, 294));

        jPanel1.setMaximumSize(new java.awt.Dimension(356, 294));
        jPanel1.setMinimumSize(new java.awt.Dimension(356, 294));
        jPanel1.setLayout(null);

        LID.setText("ID");
        jPanel1.add(LID);
        LID.setBounds(131, 52, 25, 14);

        jLabel1.setText("Bienvenidos llene los espacios solicitados");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(99, 20, 260, 14);
        jPanel1.add(CID);
        CID.setBounds(131, 72, 110, 30);

        CContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(CContraseña);
        CContraseña.setBounds(130, 130, 110, 30);

        BLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        BLogin.setText("Login");
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BLogin);
        BLogin.setBounds(130, 170, 80, 25);

        jButton6.setText("Salir ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(286, 271, 70, 23);

        LContraseña.setText("Contraseña");
        jPanel1.add(LContraseña);
        LContraseña.setBounds(130, 110, 75, 14);

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bbbbbbb.jpg"))); // NOI18N
        jPanel1.add(Imagen);
        Imagen.setBounds(0, 0, 360, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CContraseñaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

        @SuppressWarnings("empty-statement")
    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
        String ID = CID.getText();
        char[] Pass = CContraseña.getPassword();
        String Password = new String(Pass);
        System.out.print(ID);
        System.out.print(Password);
        if(!"".equals(ID) && !"".equals(Password))
        {
            for (int i = 0; i < Empleados.size(); i++) {
                if ((ID == null ? Empleados.get(i).getID() == null : ID.equals(Empleados.get(i).getID())) && (Password == null ? Empleados.get(i).getContraseña() == null : Password.equals(Empleados.get(i).getContraseña()))) {
                    EmpleadoLogeado = Empleados.get(i);
                    if (EmpleadoLogeado.Conectar_Empleado())
                    {
                        EmpleadoF EmpleadosV = new EmpleadoF();
                        EmpleadosV.setVisible(true);
                        dispose();
                        break;
                    }
                    else
                    {
                        break;
                    }
                } else {
                    if ((ID == null ? Admin.getID() == null : ID.equals(Admin.getID())) && (Password == null ? Admin.getContraseña() == null : Password.equals(Admin.getContraseña()))) {
                        EmpleadoLogeado = Admin;
                        Administrador AdminV = new Administrador();
                        AdminV.setVisible(true);
                        dispose();
                        break;

                    }
                    else
                    {
                        if (i+1==Empleados.size())
                        {
                            JOptionPane.showMessageDialog(null, "Usuario o contraseña no validos");
                        }
                    }
                }

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
    }//GEN-LAST:event_BLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
        public void AgregarEmpleados()
        {
            Empleado Oscar= new Empleado("Oscar","12345","Oscar");
            Empleados.add(Oscar);
            Empleado Alonso = new Empleado("Alonso", "12345", "Alonso");
            Empleados.add(Alonso);
            Empleado Manuel = new Empleado("Manuel", "12345", "Manuel");
            Empleados.add(Manuel);
            Empleado X = new Empleado("X", "12345", "X");
            Empleados.add(X);


        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BLogin;
    private javax.swing.JPasswordField CContraseña;
    private javax.swing.JTextField CID;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel LContraseña;
    private javax.swing.JLabel LID;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
